# Generated by Django 3.2.3 on 2021-05-31 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfProduct', models.CharField(max_length=255)),
                ('Production_Date', models.DateField()),
                ('Manufacturer', models.CharField(max_length=300)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.shopcategory')),
            ],
            options={
                'ordering': ('NameOfProduct',),
            },
        ),
    ]
